version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip ./sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.6.2.2472-linux/bin/
      # Create empty directory for binaries to satisfy SonarQube requirements
      - mkdir -p target/classes
  build:
    commands:
      - |
        sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
        -Dsonar.projectKey=$PROJECT \
        -Dsonar.projectName=$PROJECT \
        -Dsonar.sources=src/main/java \
        -Dsonar.host.url=$REVIEW_HOST \
        -Dsonar.login=$LOGIN \
        -Dsonar.sourceEncoding=UTF-8 \
        -Dsonar.java.source=17 \
        -Dsonar.java.binaries=target/classes \
        -Dsonar.scm.disabled=true \
        -Dsonar.exclusions=**/generated-sources/**/*,**/target/**/*