## Server configuration
server.port=8082
server.session.timeout=5000
server.servlet.context-path=/test
spring.main.banner-mode=off
## Application configuration
app.name=APIReward
app.domain=RWD
app.zone=LOCAL
app.private.key.aes256cbc=NEWappSq7CpRFh8jar3n5PgyuGLDmbQ2
app.key=B374A26A71490437AA024E4FADD5B497
app.fe.aes256=RTStQ76Y1bmTIiyZCor+NQPeJgWfIieu
app.iv=7E892875A52C59A3
#######################################
###      JASYPT Configuration       ###
#######################################
jasypt.encryptor.key-obtention-iterations=1000
jasypt.encryptor.pool-size=1
jasypt.encryptor.provider-name=null
jasypt.encryptor.provider-class-name=null
jasypt.encryptor.salt-generator-classname=org.jasypt.salt.RandomSaltGenerator
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.string-output-type=base64
spring.datasource.hikari.connection-test-query:SELECT 1
spring.datasource.hikari.connection-timeout=1000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.validation-timeout=1000
#######################################
### Spring DataSource Configuration ###
#######################################
# Set true for first time db initialization.
spring.sql.init.mode=ALWAYS
#common postgresql
spring.datasource.db1.jdbcUrl=jdbc:postgresql://localhost:5432/postgres
spring.datasource.db1.username=postgres
spring.datasource.db1.password=1
spring.datasource.db1.driver-class-name=org.postgresql.Driver

#cms postgresql
spring.datasource.venus.jdbcUrl=jdbc:postgresql://localhost:5432/postgres
spring.datasource.venus.username=postgres
spring.datasource.venus.password=1
spring.datasource.venus.driver-class-name=org.postgresql.Driver

spring.data.jpa.repositories.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=validate

#######################################
###   Spring Redis Configuration    ###
#######################################
spring.data.redis.database=0
spring.data.redis.host=127.0.0.1
#spring.data.redis.host=172.16.50.227
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000
spring.redis.ssl=false
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
trueapp.jwtSecretKey=asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
trueapp.apigwClientId=R7tsGgSsSf757aorElm87RulmB9CFOrU
trueapp.apigwClientSecret=VKCFTqRLrUD5M8or
spring.mvc.async.request-timeout=500
app.validate.earn.bzbProductId=21,22,23
spring.data.redis.jedis.pool.max-active=10
spring.data.redis.jedis.pool.max-idle=2
spring.data.redis.jedis.pool.min-idle=1
spring.data.redis.jedis.pool.max-wait=2000
framework.http.pool.idle.release=1000
server.tomcat.threads.max=4000
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=1000
management.endpoints.web.exposure.include=metrics,health,prometheus
management.metrics.export.prometheus.enabled=true
management.metrics.enable.tomcat=true